### ISSUE TITLE
Feature request: Child Combinator

### ISSUE THREAD

**Issue by zethraeus** [uber/NEAL#2]
I'd like to apply a rule only to ConstantDeclarations which are class properties.

I'd hoped I could achieve this by nesting the ConstantDeclaration directly within the ClassDeclaration (as below) but this matches all ConstantDeclarations within the class (as it should!).

```
rule NoSelfCapturingConstantDeclaration {
  Swift::ClassDeclaration {
    ConstantDeclaration {
```

This is a feature request for a child combinator, to allow me to target only direct decedents of a ClassDeclaration. (Perhaps in the style of the CSS child selector https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors)

**Comment by tadeuzagallo** [comment]
Yes, I had an internal ticket for adding support for that but still have to implement it. We actually need the child combinator (`>`) and the descendant combinator (`>>`), so you can restrict a nested matcher to a given property of the matched node. I'll give it a try and update it here.

**Comment by tadeuzagallo** [comment]
I create a PR (linked above), let me know if that works for you.
